- !!models.Store
   image: ""
   link: ""
   title: "Gold Complete Beer Equipment Kit (K6) with 6 Gallon Glass Carboy"
   price: 72.01
   shipping: 17.99
   soldBy: "Home Brew Ohio"
   storeType: "Equipment"
   ranking: 4

- !!models.Store
   image: ""
   link: ""
   title: "How to Brew: Everything You Need To Know To Brew Beer Right The First Time"
   price: 11.27
   shipping: 0
   soldBy: "Amazon"
   storeType: "Book"
   ranking: 4.5
