- !!models.Store
   image: "http://ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B002BU7CVM&Format=_SL110_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=hopsareabrew-20"
   link: "http://www.amazon.com/gp/product/B002BU7CVM/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B002BU7CVM&linkCode=as2&tag=hopsareabrew-20"
   title: "Gold Complete Beer Equipment Kit (K6) with 6 Gallon Glass Carboy"
   price: 72.01
   shipping: 17.99
   soldBy: "Home Brew Ohio"
   storeType: "Equipment"
   ranking: 4

- !!models.Store
   image: "http://ir-na.amazon-adsystem.com/e/ir?t=hopsareabrew-20&l=as2&o=1&a=0937381888"
   link: "http://www.amazon.com/gp/product/0937381888/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=0937381888&linkCode=as2&tag=hopsareabrew-20"
   title: "How to Brew: Everything You Need To Know To Brew Beer Right The First Time"
   price: 11.27
   shipping: 0
   soldBy: "Amazon"
   storeType: "Book"
   ranking: 4.5
